// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

@class Person;
@class Person_Builder;

@interface PersonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Person : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasEmail_:1;
  int32_t id;
  NSString* name;
  NSString* email;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasEmail;
@property (readonly) int32_t id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* email;

+ (Person*) defaultInstance;
- (Person*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Person_Builder*) builder;
+ (Person_Builder*) builder;
+ (Person_Builder*) builderWithPrototype:(Person*) prototype;

+ (Person*) parseFromData:(NSData*) data;
+ (Person*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromInputStream:(NSInputStream*) input;
+ (Person*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Person*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Person_Builder : PBGeneratedMessageBuilder {
@private
  Person* result;
}

- (Person*) defaultInstance;

- (Person_Builder*) clear;
- (Person_Builder*) clone;

- (Person*) build;
- (Person*) buildPartial;

- (Person_Builder*) mergeFrom:(Person*) other;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Person_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (int32_t) id;
- (Person_Builder*) setId:(int32_t) value;
- (Person_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (Person_Builder*) setName:(NSString*) value;
- (Person_Builder*) clearName;

- (BOOL) hasEmail;
- (NSString*) email;
- (Person_Builder*) setEmail:(NSString*) value;
- (Person_Builder*) clearEmail;
@end

